# Generated by Django 5.2 on 2025-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adddress',
            new_name='address',
        ),
    ]
